<a href="https://colab.research.google.com/github/giolanta-nta/Homework/blob/main/Practice_ML_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import pandas as pd

In [3]:
personal_data = {'Onoma': ['Maria','Giorgos','Petros','Vasiliki','Alexandra', 'Popi'],
            'Ilikia':[22,38,31,19,29,49],
            'Poli':['Athens','Patra','Trikala','Sparti','Serres', 'Chios'], 'Epaggelma':['foititria','ilektrologos','kathigitis', 'foititria', 'anergi', 'daskala']}

In [19]:
df = pd.DataFrame(personal_data)
print(df)

       Onoma  Ilikia     Poli     Epaggelma
0      Maria      22   Athens     foititria
1    Giorgos      38    Patra  ilektrologos
2     Petros      31  Trikala    kathigitis
3   Vasiliki      19   Sparti     foititria
4  Alexandra      29   Serres        anergi
5       Popi      49    Chios       daskala

In [45]:
df.dtypes

Onoma        object
lesson       object
mathima      object
Ilikia        int64
Poli         object
Epaggelma    object
dtype: object

In [44]:
df[df['Onoma'] == 'Maria']

   Onoma lesson mathima  Ilikia    Poli  Epaggelma
0  Maria      A       A      22  Athens  foititria

In [42]:
df.loc[5]

Onoma           Popi
lesson             A
mathima            A
Ilikia            49
Poli           Chios
Epaggelma    daskala
Name: 5, dtype: object

In [11]:
df.iloc[1]

Onoma             Giorgos
Ilikia                 38
Poli                Patra
Epaggelma    ilektrologos
Name: 1, dtype: object

In [14]:
print(df.iloc [ :, [1, 2]])

   Ilikia     Poli
0      22   Athens
1      38    Patra
2      31  Trikala
3      19   Sparti
4      29   Serres
5      49    Chios

In [22]:
df.loc[0:3]

      Onoma  Ilikia     Poli     Epaggelma
0     Maria      22   Athens     foititria
1   Giorgos      38    Patra  ilektrologos
2    Petros      31  Trikala    kathigitis
3  Vasiliki      19   Sparti     foititria

In [31]:
df.iloc[0:3, 2:4]

      Poli     Epaggelma
0   Athens     foititria
1    Patra  ilektrologos
2  Trikala    kathigitis

In [46]:
df.set_index('Onoma', inplace=True)

In [48]:
print(df)

          lesson mathima  Ilikia     Poli     Epaggelma
Onoma
Maria          A       A      22   Athens     foititria
Giorgos        A       A      38    Patra  ilektrologos
Petros         A       A      31  Trikala    kathigitis
Vasiliki       A       A      19   Sparti     foititria
Alexandra      A       A      29   Serres        anergi
Popi           A       A      49    Chios       daskala

In [50]:
df.loc['Maria']

lesson               A
mathima              A
Ilikia              22
Poli            Athens
Epaggelma    foititria
Name: Maria, dtype: object

In [53]:
df.loc['Popi']

lesson             A
mathima            A
Ilikia            49
Poli           Chios
Epaggelma    daskala
Name: Popi, dtype: object

In [61]:
df=pd.read_csv("https://raw.githubusercontent.com/datajour-gr/ML-algorithms/refs/heads/master/week%204/alzheimer.csv", sep=";")

In [62]:
df.dtypes

ID        int64
MMSE    float64
sex      object
city     object
age     float64
dtype: object

In [63]:
df.shape

(45, 5)

In [64]:
df.head(10)

   ID  MMSE sex    city    age
0   1  16.0   F  Vienna   65.0
1   2  25.0   F    Linz   66.0
2   3  20.0   F    Graz   58.0
3   4  26.0   F    Graz  999.0
4   5  10.0   F  Vienna   64.0
5   6  18.0   F  Vienna   73.0
6   7  19.0   F    9999    NaN
7   9  14.0   F  Vienna   68.0
8  10  22.0   F    Graz   74.0
9   8   NaN   F    Linz   59.0

In [65]:
df.set_index('ID')

    MMSE  sex    city    age
ID
1   16.0    F  Vienna   65.0
2   25.0    F    Linz   66.0
3   20.0    F    Graz   58.0
4   26.0    F    Graz  999.0
5   10.0    F  Vienna   64.0
6   18.0    F  Vienna   73.0
7   19.0    F    9999    NaN
9   14.0    F  Vienna   68.0
10  22.0    F    Graz   74.0
8    NaN    F    Linz   59.0
11  18.0    F    Linz   58.0
12  28.0    F    Graz   76.0
13  27.0    M    Graz   62.0
14  23.0    M  Vienna   68.0
15  28.0    M  Vienna   77.0
16  35.0    M  Vienna   59.0
17  18.0  NaN  Vienna   66.0
18  19.0    M  Vienna   64.0
19  22.0    M    Graz   68.0
20  29.0    M    Graz   70.0
21  23.0    M  Vienna   71.0
22  21.0    M    Linz   69.0
23  11.0    F    Linz    NaN
24  29.0    F    Graz   68.0
25  35.0    F  Vienna   74.0
26  22.0    F  Vienna   68.0
27   NaN    F     NaN   68.0
28  33.0    F  Vienna   69.0
29  21.0    F     NaN   59.0
30  20.0    F  Vienna   61.0
31  26.0    F    Graz   71.0
32  26.0    M    Graz   68.0
33  28.0    F    Graz   64.0
34  32.0    F  Vienna   63.0
35  32.0    F  Vienna    NaN
36  20.0    M  Vienna   68.0
37  35.0    M  Vienna   65.0
38   NaN    M    Linz   66.0
39  39.0    M    Linz   64.0
40  27.0    M    Linz   77.0
41  23.0    F    Linz   59.0
42  24.0    F  Vienna   58.0
43  21.0    F    Graz   73.0
44  19.0    M    Graz   70.0
45  27.0    M  Vienna   71.0

In [68]:
df.iloc[1:10]

   ID  MMSE sex    city    age
1   2  25.0   F    Linz   66.0
2   3  20.0   F    Graz   58.0
3   4  26.0   F    Graz  999.0
4   5  10.0   F  Vienna   64.0
5   6  18.0   F  Vienna   73.0
6   7  19.0   F    9999    NaN
7   9  14.0   F  Vienna   68.0
8  10  22.0   F    Graz   74.0
9   8   NaN   F    Linz   59.0

In [72]:
df['sex'].value_counts()

sex
F    27
M    17
Name: count, dtype: int64

In [76]:
df[df['sex'] == 'F'].sort_values(by='MMSE', ascending=False)

    ID  MMSE sex    city    age
24  25  35.0   F  Vienna   74.0
27  28  33.0   F  Vienna   69.0
34  35  32.0   F  Vienna    NaN
33  34  32.0   F  Vienna   63.0
23  24  29.0   F    Graz   68.0
32  33  28.0   F    Graz   64.0
11  12  28.0   F    Graz   76.0
30  31  26.0   F    Graz   71.0
3    4  26.0   F    Graz  999.0
1    2  25.0   F    Linz   66.0
41  42  24.0   F  Vienna   58.0
40  41  23.0   F    Linz   59.0
25  26  22.0   F  Vienna   68.0
8   10  22.0   F    Graz   74.0
28  29  21.0   F     NaN   59.0
42  43  21.0   F    Graz   73.0
2    3  20.0   F    Graz   58.0
29  30  20.0   F  Vienna   61.0
6    7  19.0   F    9999    NaN
10  11  18.0   F    Linz   58.0
5    6  18.0   F  Vienna   73.0
0    1  16.0   F  Vienna   65.0
7    9  14.0   F  Vienna   68.0
22  23  11.0   F    Linz    NaN
4    5  10.0   F  Vienna   64.0
9    8   NaN   F    Linz   59.0
26  27   NaN   F     NaN   68.0

In [77]:
df['MMSE'].mean()

np.float64(24.071428571428573)

In [81]:
df[df['MMSE'] > df['MMSE'].mean()]

    ID  MMSE sex    city    age
1    2  25.0   F    Linz   66.0
3    4  26.0   F    Graz  999.0
11  12  28.0   F    Graz   76.0
12  13  27.0   M    Graz   62.0
14  15  28.0   M  Vienna   77.0
15  16  35.0   M  Vienna   59.0
19  20  29.0   M    Graz   70.0
23  24  29.0   F    Graz   68.0
24  25  35.0   F  Vienna   74.0
27  28  33.0   F  Vienna   69.0
30  31  26.0   F    Graz   71.0
31  32  26.0   M    Graz   68.0
32  33  28.0   F    Graz   64.0
33  34  32.0   F  Vienna   63.0
34  35  32.0   F  Vienna    NaN
36  37  35.0   M  Vienna   65.0
38  39  39.0   M    Linz   64.0
39  40  27.0   M    Linz   77.0
44  45  27.0   M  Vienna   71.0

In [87]:
df[(df['sex'] == 'F') & (df['MMSE'] > df['MMSE'].mean())]

    ID  MMSE sex    city    age
1    2  25.0   F    Linz   66.0
3    4  26.0   F    Graz  999.0
11  12  28.0   F    Graz   76.0
23  24  29.0   F    Graz   68.0
24  25  35.0   F  Vienna   74.0
27  28  33.0   F  Vienna   69.0
30  31  26.0   F    Graz   71.0
32  33  28.0   F    Graz   64.0
33  34  32.0   F  Vienna   63.0
34  35  32.0   F  Vienna    NaN

In [94]:
df[(df['sex'] == 'F') & (df['MMSE'] > df['MMSE'].mean())].shape[0]

10

In [103]:
df[(df['city'] == 'Linz') & (df['sex'] == 'M') & df['MMSE'] > df['MMSE'].mean()].shape[0]

0

In [104]:
df[(df['sex'] == 'M') & df['MMSE'] > df['MMSE'].mean()]

Empty DataFrame
Columns: [ID, MMSE, sex, city, age]
Index: []

In [105]:
df = pd.read_excel("/content/info_participants_NAs.xlsx")

In [106]:
df.dtypes

ID               int64
sex             object
satisfaction     int64
dtype: object

In [107]:
df.shape

(15, 3)

In [108]:
df.head()

   ID sex  satisfaction
0   1   m             5
1   2   w             5
2   3   m             8
3   4   w            10
4   5   m             1

In [109]:
df.set_index('ID')

   sex  satisfaction
ID
1    m             5
2    w             5
3    m             8
4    w            10
5    m             1
6    w             4
7    m             2
8    w             7
9    m             7
10   w            10
11   m             1
12   w             1
13   m             0
14   w             1
15   m             7

In [110]:
df['satisfaction'].mean()

np.float64(4.6)

In [117]:
df[(df['sex'] == 'w') & (df['satisfaction'] > df['satisfaction'].mean())]

   ID sex  satisfaction
1   2   w             5
3   4   w            10
7   8   w             7
9  10   w            10

In [118]:
df[(df['sex'] == 'm') & (df['satisfaction'] > df['satisfaction'].mean())]

    ID sex  satisfaction
0    1   m             5
2    3   m             8
8    9   m             7
14  15   m             7

In [116]:
df.groupby('sex')['satisfaction'].mean()

sex
m    3.875000
w    5.428571
Name: satisfaction, dtype: float64